### ISSUE TITLE
Does `multilspy` support parsing C code?

### ISSUE THREAD

**Issue by yz-qiang** [microsoft/multilspy#19]
Thank you for developing and maintaining `multilspy`. I have been exploring its capabilities and wanted to know if it currently supports parsing `C` code. 

If it does not support `C` code, could you please guide me on how I might extend `multilspy` to enable it to parse `C` code? 

I'm looking forward to hearing back from you. 
Thanks in advance!

**Comment by LakshyAAAgrawal** [comment]
Hi @yz-qiang ,

At the moment, multilspy doesn't have a C/C++ language server integration. In #5, I have shared the general steps to add support for a new language, and you can see an example PR adding support for a new language in #6. For C/C++ specifically, I have listed the promising language servers that I hope will work with multilspy in #14.

I welcome you to review these, and would be happy to work with you to add C/C++ support to multilspy!

**Comment by LakshyAAAgrawal** [comment]
Closing this to continue C/C++ support discussion in https://github.com/microsoft/multilspy/issues/14
